# Getting Started 
## Starting Point: SparkSession

In [0]:
# To create a basic SparkSession, just use SparkSession.builder:
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()

- SparkSession in Spark 2.0 provides builtin support for Hive features

## Creating DataFrames
- With a SparkSession, applications can create DataFrames from an existing RDD, from a Hive table, or from Spark data sources

In [0]:
# spark is an existing SparkSession
df = spark.read.json("/FileStore/tables/data.json")
# Displays the content of the DataFrame to stdout
df.show()

+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|         id|            location|sampling_rate|              sensor|    sensordatavalues|          timestamp|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|10404887592|{-6.1, NL, 0, 212...|         null|{35121, 11, {17, ...|[{23072586045, -1...|2022-05-08 14:08:02|
|10404887589|{304.9, DE, 0, 32...|         null|{46899, 1, {14, N...|[{23072586029, 2....|2022-05-08 14:08:02|
|10404887585|{34.4, BE, 0, 441...|         null|{8766, 7, {9, var...|[{23072586035, 24...|2022-05-08 14:08:02|
|10404887581|{1.0, NL, 0, 3956...|         null|{53660, 1, {14, N...|[{23072586022, 12...|2022-05-08 14:08:02|
|10404887580|{181.3, DE, 0, 10...|         null|{19948, 3, {8, Bo...|[{23072586026, 10...|2022-05-08 14:08:02|
|10404887579|{282.0, DE, 0, 36...|         null|{7231, 1, {14, No...|[{23072586023, 6....|2022-05-08 14:08:02|
|10404887578|{0.9, NL, 0, 3851...|         null|{51618, 1, {14, N...|[{23072586017, 8....|2022-05-08 14:08:02|
|10404887577|{577.1, BG, 0, 42...|         null|{56830, 1, {14, N...|[{23072586012, 6....|2022-05-08 14:08:02|
|10404887576|{9.2, NL, 0, 4328...|         null|{57443, 1, {14, N...|[{23072586036, 5....|2022-05-08 14:08:02|
|10404887575|{124.5, DE, 0, 34...|         null|{6755, 1, {14, No...|[{23072586008, 1....|2022-05-08 14:08:02|
|10404887574|{476.4, DE, 0, 16...|         null|{30149, 1, {14, N...|[{23072586006, 4....|2022-05-08 14:08:02|
|10404887573|{320.5, PL, 0, 57...|         null|{67396, 1, {37, S...|[{23072586007, 4....|2022-05-08 14:08:01|
|10404887572|{479.3, DE, 0, 35...|         null|{7016, 7, {9, var...|[{23072586003, 16...|2022-05-08 14:08:02|
|10404887571|{195.0, DE, 1, 42...|         null|{56480, 11, {17, ...|[{23072586014, 38...|2022-05-08 14:08:02|
|10404887570|{52.0, DE, 1, 402...|         null|{54380, 15, {29, ...|[{23072586016, 49...|2022-05-08 14:08:01|
|10404887569|{-2.5, NL, 1, 573...|         null|{70055, 7, {9, va...|[{23072586011, 25...|2022-05-08 14:08:01|
|10404887568|{11.0, NL, 0, 524...|         null|{60292, 1, {14, N...|[{23072585998, 8....|2022-05-08 14:08:01|
|10404887566|{112.5, DE, 0, 59...|         null|{71435, 1, {14, N...|[{23072585995, 9....|2022-05-08 14:08:01|
|10404887565|{163.5, PL, 0, 12...|         null|{23340, 1, {14, N...|[{23072586004, 4....|2022-05-08 14:08:01|
|10404887564|{427.9, DE, 0, 96...|         null|{19076, 1, {14, N...|[{23072585994, 3....|2022-05-08 14:08:01|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
only showing top 20 rows

## Untyped Dataset Operations (aka DataFrame Operations)
- in Spark 2.0, DataFrames are just Dataset of Rows in Scala and Java API. 
- These operations are also referred as “untyped transformations” in contrast to “typed transformations” come with strongly typed Scala/Java Datasets
- In Python,  DataFrame’s columns accesses : by attribute (df.age) or by indexing (df['age'])

In [0]:
# spark, df are from the previous example
# Print the schema in a tree format
df.printSchema()

root
 |-- id: long (nullable = true)
 |-- location: struct (nullable = true)
 |    |-- altitude: string (nullable = true)
 |    |-- country: string (nullable = true)
 |    |-- exact_location: long (nullable = true)
 |    |-- id: long (nullable = true)
 |    |-- indoor: long (nullable = true)
 |    |-- latitude: string (nullable = true)
 |    |-- longitude: string (nullable = true)
 |-- sampling_rate: long (nullable = true)
 |-- sensor: struct (nullable = true)
 |    |-- id: long (nullable = true)
 |    |-- pin: string (nullable = true)
 |    |-- sensor_type: struct (nullable = true)
 |    |    |-- id: long (nullable = true)
 |    |    |-- manufacturer: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |-- sensordatavalues: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: long (nullable = true)
 |    |    |-- value: string (nullable = true)
 |    |    |-- value_type: string (nullable = true)
 |-- timestamp: string (nullable = true)

+-----------+
|         id|
+-----------+
|10404887592|
|10404887589|
|10404887585|
|10404887581|
|10404887580|
|10404887579|
|10404887578|
|10404887577|
|10404887576|
|10404887575|
|10404887574|
|10404887573|
|10404887572|
|10404887571|
|10404887570|
|10404887569|
|10404887568|
|10404887566|
|10404887565|
|10404887564|
+-----------+
only showing top 20 rows

+-----------+-----------+
|         id|   (id + 1)|
+-----------+-----------+
|10404887592|10404887593|
|10404887589|10404887590|
|10404887585|10404887586|
|10404887581|10404887582|
|10404887580|10404887581|
|10404887579|10404887580|
|10404887578|10404887579|
|10404887577|10404887578|
|10404887576|10404887577|
|10404887575|10404887576|
|10404887574|10404887575|
|10404887573|10404887574|
|10404887572|10404887573|
|10404887571|10404887572|
|10404887570|10404887571|
|10404887569|10404887570|
|10404887568|10404887569|
|10404887566|10404887567|
|10404887565|10404887566|
|10404887564|10404887565|
+-----------+-----------+
only showing top 20 rows

+---+--------+-------------+------+----------------+---------+
| id|location|sampling_rate|sensor|sensordatavalues|timestamp|
+---+--------+-------------+------+----------------+---------+
+---+--------+-------------+------+----------------+---------+

In [0]:
# select
df.select("id").show()

+-----------+
|         id|
+-----------+
|10404887592|
|10404887589|
|10404887585|
|10404887581|
|10404887580|
|10404887579|
|10404887578|
|10404887577|
|10404887576|
|10404887575|
|10404887574|
|10404887573|
|10404887572|
|10404887571|
|10404887570|
|10404887569|
|10404887568|
|10404887566|
|10404887565|
|10404887564|
+-----------+
only showing top 20 rows

+-----------+-----------+
|         id|   (id + 1)|
+-----------+-----------+
|10404887592|10404887593|
|10404887589|10404887590|
|10404887585|10404887586|
|10404887581|10404887582|
|10404887580|10404887581|
|10404887579|10404887580|
|10404887578|10404887579|
|10404887577|10404887578|
|10404887576|10404887577|
|10404887575|10404887576|
|10404887574|10404887575|
|10404887573|10404887574|
|10404887572|10404887573|
|10404887571|10404887572|
|10404887570|10404887571|
|10404887569|10404887570|
|10404887568|10404887569|
|10404887566|10404887567|
|10404887565|10404887566|
|10404887564|10404887565|
+-----------+-----------+
only showing top 20 rows

+---+--------+-------------+------+----------------+---------+
| id|location|sampling_rate|sensor|sensordatavalues|timestamp|
+---+--------+-------------+------+----------------+---------+
+---+--------+-------------+------+----------------+---------+

In [0]:
# Select everybody, but increment the age by 1
df.select(df['id'], df['id'] + 1).show()

+-----------+-----------+
|         id|   (id + 1)|
+-----------+-----------+
|10404887592|10404887593|
|10404887589|10404887590|
|10404887585|10404887586|
|10404887581|10404887582|
|10404887580|10404887581|
|10404887579|10404887580|
|10404887578|10404887579|
|10404887577|10404887578|
|10404887576|10404887577|
|10404887575|10404887576|
|10404887574|10404887575|
|10404887573|10404887574|
|10404887572|10404887573|
|10404887571|10404887572|
|10404887570|10404887571|
|10404887569|10404887570|
|10404887568|10404887569|
|10404887566|10404887567|
|10404887565|10404887566|
|10404887564|10404887565|
+-----------+-----------+
only showing top 20 rows

In [0]:
# Select people older than 21
df.filter(df['id'] < 10404887589).show()

+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|         id|            location|sampling_rate|              sensor|    sensordatavalues|          timestamp|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|10404887585|{34.4, BE, 0, 441...|         null|{8766, 7, {9, var...|[{23072586035, 24...|2022-05-08 14:08:02|
|10404887581|{1.0, NL, 0, 3956...|         null|{53660, 1, {14, N...|[{23072586022, 12...|2022-05-08 14:08:02|
|10404887580|{181.3, DE, 0, 10...|         null|{19948, 3, {8, Bo...|[{23072586026, 10...|2022-05-08 14:08:02|
|10404887579|{282.0, DE, 0, 36...|         null|{7231, 1, {14, No...|[{23072586023, 6....|2022-05-08 14:08:02|
|10404887578|{0.9, NL, 0, 3851...|         null|{51618, 1, {14, N...|[{23072586017, 8....|2022-05-08 14:08:02|
|10404887577|{577.1, BG, 0, 42...|         null|{56830, 1, {14, N...|[{23072586012, 6....|2022-05-08 14:08:02|
|10404887576|{9.2, NL, 0, 4328...|         null|{57443, 1, {14, N...|[{23072586036, 5....|2022-05-08 14:08:02|
|10404887575|{124.5, DE, 0, 34...|         null|{6755, 1, {14, No...|[{23072586008, 1....|2022-05-08 14:08:02|
|10404887574|{476.4, DE, 0, 16...|         null|{30149, 1, {14, N...|[{23072586006, 4....|2022-05-08 14:08:02|
|10404887573|{320.5, PL, 0, 57...|         null|{67396, 1, {37, S...|[{23072586007, 4....|2022-05-08 14:08:01|
|10404887572|{479.3, DE, 0, 35...|         null|{7016, 7, {9, var...|[{23072586003, 16...|2022-05-08 14:08:02|
|10404887571|{195.0, DE, 1, 42...|         null|{56480, 11, {17, ...|[{23072586014, 38...|2022-05-08 14:08:02|
|10404887570|{52.0, DE, 1, 402...|         null|{54380, 15, {29, ...|[{23072586016, 49...|2022-05-08 14:08:01|
|10404887569|{-2.5, NL, 1, 573...|         null|{70055, 7, {9, va...|[{23072586011, 25...|2022-05-08 14:08:01|
|10404887568|{11.0, NL, 0, 524...|         null|{60292, 1, {14, N...|[{23072585998, 8....|2022-05-08 14:08:01|
|10404887566|{112.5, DE, 0, 59...|         null|{71435, 1, {14, N...|[{23072585995, 9....|2022-05-08 14:08:01|
|10404887565|{163.5, PL, 0, 12...|         null|{23340, 1, {14, N...|[{23072586004, 4....|2022-05-08 14:08:01|
|10404887564|{427.9, DE, 0, 96...|         null|{19076, 1, {14, N...|[{23072585994, 3....|2022-05-08 14:08:01|
|10404887563|{62.0, US, 0, 349...|         null|{48643, 1, {23, P...|[{23072586000, 0,...|2022-05-08 14:08:01|
|10404887562|{324.6, DE, 1, 54...|         null|{67742, 7, {27, S...|[{23072585992, 26...|2022-05-08 14:08:01|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
only showing top 20 rows

In [0]:
# Count people by age
df.groupBy(df['location']['altitude']).count().show()

+------------------+-----+
|location[altitude]|count|
+------------------+-----+
|             286.9|   14|
|              73.7|   51|
|              91.8|   11|
|             429.6|   16|
|             406.6|    6|
|              10.7|   50|
|             118.5|   21|
|             480.5|   30|
|             191.9|   12|
|               8.5|   42|
|             110.9|   35|
|              78.9|   21|
|             262.7|    7|
|             119.8|   18|
|             291.9|   10|
|             471.9|    4|
|             483.7|   47|
|             102.0|   18|
|             151.0|   10|
|             684.3|    2|
+------------------+-----+
only showing top 20 rows

## Running SQL Queries Programmatically
- The sql function on a SparkSession enables applications to run SQL queries programmatically and returns the result as a DataFrame.

In [0]:
# Register the DataFrame as a SQL temporary view
df.createOrReplaceTempView("data")

sqlDF = spark.sql("SELECT * FROM data")
sqlDF.show()

+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|         id|            location|sampling_rate|              sensor|    sensordatavalues|          timestamp|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|10404887592|{-6.1, NL, 0, 212...|         null|{35121, 11, {17, ...|[{23072586045, -1...|2022-05-08 14:08:02|
|10404887589|{304.9, DE, 0, 32...|         null|{46899, 1, {14, N...|[{23072586029, 2....|2022-05-08 14:08:02|
|10404887585|{34.4, BE, 0, 441...|         null|{8766, 7, {9, var...|[{23072586035, 24...|2022-05-08 14:08:02|
|10404887581|{1.0, NL, 0, 3956...|         null|{53660, 1, {14, N...|[{23072586022, 12...|2022-05-08 14:08:02|
|10404887580|{181.3, DE, 0, 10...|         null|{19948, 3, {8, Bo...|[{23072586026, 10...|2022-05-08 14:08:02|
|10404887579|{282.0, DE, 0, 36...|         null|{7231, 1, {14, No...|[{23072586023, 6....|2022-05-08 14:08:02|
|10404887578|{0.9, NL, 0, 3851...|         null|{51618, 1, {14, N...|[{23072586017, 8....|2022-05-08 14:08:02|
|10404887577|{577.1, BG, 0, 42...|         null|{56830, 1, {14, N...|[{23072586012, 6....|2022-05-08 14:08:02|
|10404887576|{9.2, NL, 0, 4328...|         null|{57443, 1, {14, N...|[{23072586036, 5....|2022-05-08 14:08:02|
|10404887575|{124.5, DE, 0, 34...|         null|{6755, 1, {14, No...|[{23072586008, 1....|2022-05-08 14:08:02|
|10404887574|{476.4, DE, 0, 16...|         null|{30149, 1, {14, N...|[{23072586006, 4....|2022-05-08 14:08:02|
|10404887573|{320.5, PL, 0, 57...|         null|{67396, 1, {37, S...|[{23072586007, 4....|2022-05-08 14:08:01|
|10404887572|{479.3, DE, 0, 35...|         null|{7016, 7, {9, var...|[{23072586003, 16...|2022-05-08 14:08:02|
|10404887571|{195.0, DE, 1, 42...|         null|{56480, 11, {17, ...|[{23072586014, 38...|2022-05-08 14:08:02|
|10404887570|{52.0, DE, 1, 402...|         null|{54380, 15, {29, ...|[{23072586016, 49...|2022-05-08 14:08:01|
|10404887569|{-2.5, NL, 1, 573...|         null|{70055, 7, {9, va...|[{23072586011, 25...|2022-05-08 14:08:01|
|10404887568|{11.0, NL, 0, 524...|         null|{60292, 1, {14, N...|[{23072585998, 8....|2022-05-08 14:08:01|
|10404887566|{112.5, DE, 0, 59...|         null|{71435, 1, {14, N...|[{23072585995, 9....|2022-05-08 14:08:01|
|10404887565|{163.5, PL, 0, 12...|         null|{23340, 1, {14, N...|[{23072586004, 4....|2022-05-08 14:08:01|
|10404887564|{427.9, DE, 0, 96...|         null|{19076, 1, {14, N...|[{23072585994, 3....|2022-05-08 14:08:01|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
only showing top 20 rows

## Global Temporary View
- Temporary views in Spark SQL are session-scoped and will disappear if the session that creates it terminates.
- If you want to have a temporary view that is shared among all sessions and keep alive until the Spark application terminates, you can create a global temporary view. 
- Global temporary view is tied to a system preserved database global_temp, and we must use the qualified name to refer it, e.g. SELECT * FROM global_temp.view1.

In [0]:
# Register the DataFrame as a global temporary view
df.createGlobalTempView("data")

# Global temporary view is tied to a system preserved database `global_temp`
spark.sql("SELECT * FROM global_temp.data").show()

# Global temporary view is cross-session
spark.newSession().sql("SELECT * FROM global_temp.data").show()

+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|         id|            location|sampling_rate|              sensor|    sensordatavalues|          timestamp|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|10404887592|{-6.1, NL, 0, 212...|         null|{35121, 11, {17, ...|[{23072586045, -1...|2022-05-08 14:08:02|
|10404887589|{304.9, DE, 0, 32...|         null|{46899, 1, {14, N...|[{23072586029, 2....|2022-05-08 14:08:02|
|10404887585|{34.4, BE, 0, 441...|         null|{8766, 7, {9, var...|[{23072586035, 24...|2022-05-08 14:08:02|
|10404887581|{1.0, NL, 0, 3956...|         null|{53660, 1, {14, N...|[{23072586022, 12...|2022-05-08 14:08:02|
|10404887580|{181.3, DE, 0, 10...|         null|{19948, 3, {8, Bo...|[{23072586026, 10...|2022-05-08 14:08:02|
|10404887579|{282.0, DE, 0, 36...|         null|{7231, 1, {14, No...|[{23072586023, 6....|2022-05-08 14:08:02|
|10404887578|{0.9, NL, 0, 3851...|         null|{51618, 1, {14, N...|[{23072586017, 8....|2022-05-08 14:08:02|
|10404887577|{577.1, BG, 0, 42...|         null|{56830, 1, {14, N...|[{23072586012, 6....|2022-05-08 14:08:02|
|10404887576|{9.2, NL, 0, 4328...|         null|{57443, 1, {14, N...|[{23072586036, 5....|2022-05-08 14:08:02|
|10404887575|{124.5, DE, 0, 34...|         null|{6755, 1, {14, No...|[{23072586008, 1....|2022-05-08 14:08:02|
|10404887574|{476.4, DE, 0, 16...|         null|{30149, 1, {14, N...|[{23072586006, 4....|2022-05-08 14:08:02|
|10404887573|{320.5, PL, 0, 57...|         null|{67396, 1, {37, S...|[{23072586007, 4....|2022-05-08 14:08:01|
|10404887572|{479.3, DE, 0, 35...|         null|{7016, 7, {9, var...|[{23072586003, 16...|2022-05-08 14:08:02|
|10404887571|{195.0, DE, 1, 42...|         null|{56480, 11, {17, ...|[{23072586014, 38...|2022-05-08 14:08:02|
|10404887570|{52.0, DE, 1, 402...|         null|{54380, 15, {29, ...|[{23072586016, 49...|2022-05-08 14:08:01|
|10404887569|{-2.5, NL, 1, 573...|         null|{70055, 7, {9, va...|[{23072586011, 25...|2022-05-08 14:08:01|
|10404887568|{11.0, NL, 0, 524...|         null|{60292, 1, {14, N...|[{23072585998, 8....|2022-05-08 14:08:01|
|10404887566|{112.5, DE, 0, 59...|         null|{71435, 1, {14, N...|[{23072585995, 9....|2022-05-08 14:08:01|
|10404887565|{163.5, PL, 0, 12...|         null|{23340, 1, {14, N...|[{23072586004, 4....|2022-05-08 14:08:01|
|10404887564|{427.9, DE, 0, 96...|         null|{19076, 1, {14, N...|[{23072585994, 3....|2022-05-08 14:08:01|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
only showing top 20 rows

+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|         id|            location|sampling_rate|              sensor|    sensordatavalues|          timestamp|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
|10404887592|{-6.1, NL, 0, 212...|         null|{35121, 11, {17, ...|[{23072586045, -1...|2022-05-08 14:08:02|
|10404887589|{304.9, DE, 0, 32...|         null|{46899, 1, {14, N...|[{23072586029, 2....|2022-05-08 14:08:02|
|10404887585|{34.4, BE, 0, 441...|         null|{8766, 7, {9, var...|[{23072586035, 24...|2022-05-08 14:08:02|
|10404887581|{1.0, NL, 0, 3956...|         null|{53660, 1, {14, N...|[{23072586022, 12...|2022-05-08 14:08:02|
|10404887580|{181.3, DE, 0, 10...|         null|{19948, 3, {8, Bo...|[{23072586026, 10...|2022-05-08 14:08:02|
|10404887579|{282.0, DE, 0, 36...|         null|{7231, 1, {14, No...|[{23072586023, 6....|2022-05-08 14:08:02|
|10404887578|{0.9, NL, 0, 3851...|         null|{51618, 1, {14, N...|[{23072586017, 8....|2022-05-08 14:08:02|
|10404887577|{577.1, BG, 0, 42...|         null|{56830, 1, {14, N...|[{23072586012, 6....|2022-05-08 14:08:02|
|10404887576|{9.2, NL, 0, 4328...|         null|{57443, 1, {14, N...|[{23072586036, 5....|2022-05-08 14:08:02|
|10404887575|{124.5, DE, 0, 34...|         null|{6755, 1, {14, No...|[{23072586008, 1....|2022-05-08 14:08:02|
|10404887574|{476.4, DE, 0, 16...|         null|{30149, 1, {14, N...|[{23072586006, 4....|2022-05-08 14:08:02|
|10404887573|{320.5, PL, 0, 57...|         null|{67396, 1, {37, S...|[{23072586007, 4....|2022-05-08 14:08:01|
|10404887572|{479.3, DE, 0, 35...|         null|{7016, 7, {9, var...|[{23072586003, 16...|2022-05-08 14:08:02|
|10404887571|{195.0, DE, 1, 42...|         null|{56480, 11, {17, ...|[{23072586014, 38...|2022-05-08 14:08:02|
|10404887570|{52.0, DE, 1, 402...|         null|{54380, 15, {29, ...|[{23072586016, 49...|2022-05-08 14:08:01|
|10404887569|{-2.5, NL, 1, 573...|         null|{70055, 7, {9, va...|[{23072586011, 25...|2022-05-08 14:08:01|
|10404887568|{11.0, NL, 0, 524...|         null|{60292, 1, {14, N...|[{23072585998, 8....|2022-05-08 14:08:01|
|10404887566|{112.5, DE, 0, 59...|         null|{71435, 1, {14, N...|[{23072585995, 9....|2022-05-08 14:08:01|
|10404887565|{163.5, PL, 0, 12...|         null|{23340, 1, {14, N...|[{23072586004, 4....|2022-05-08 14:08:01|
|10404887564|{427.9, DE, 0, 96...|         null|{19076, 1, {14, N...|[{23072585994, 3....|2022-05-08 14:08:01|
+-----------+--------------------+-------------+--------------------+--------------------+-------------------+
only showing top 20 rows

## Interoperating with RDDs
- Spark SQL supports two different methods for converting existing RDDs into Datasets.
- (1) reflection-based approach : infer the schema of an RDD that contains specific types of objects
- (2) using programmatic interface : construct a schema and then apply it to an existing RDD

## Inferring the Schema Using Reflection
- Spark SQL can convert an RDD of Row objects to a DataFrame, inferring the datatypes.
- Rows are constructed by passing a list of key/value pairs as kwargs to the Row class.
- The keys of this list define the column names of the table, and the types are inferred by sampling the whole dataset, similar to the inference that is performed on JSON files.

In [0]:
from pyspark.sql import Row

sc = spark.sparkContext

# Load a text file and convert each line to a Row.
# lines, parts, people is RDD 
lines = sc.textFile("/FileStore/people.txt") 
parts = lines.map(lambda l: l.split(",")) 
people = parts.map(lambda p: Row(name=p[0], age=int(p[1])))

# Infer the schema, and register the DataFrame as a table.
schemaPeople = spark.createDataFrame(people)
schemaPeople.createOrReplaceTempView("people")

# SQL can be run over DataFrames that have been registered as a table.
teenagers = spark.sql("SELECT name FROM people WHERE age >= 13 AND age <= 19")

# The results of SQL queries are Dataframe objects.
# rdd returns the content as an :class:`pyspark.RDD` of :class:`Row`.
teenNames = teenagers.rdd.map(lambda p: "Name: " + p.name).collect()
for name in teenNames:
    print(name)
# Name: Justin

Name: Justin

## Programmatically Specifying the Schema
- When a dictionary of kwargs cannot be defined ahead of time, a DataFrame can be created programmatically with three steps.
  - (1) Create an RDD of tuples or lists from the original RDD;
  - (2) Create the schema represented by a StructType matching the structure of tuples or lists in the RDD created in the step 1.
  - (3) Apply the schema to the RDD via createDataFrame method provided by SparkSession.

In [0]:
# Import data types
from pyspark.sql.types import StringType, StructType, StructField

sc = spark.sparkContext

# Load a text file and convert each line to a Row.
lines = sc.textFile("/FileStore/people.txt")
parts = lines.map(lambda l: l.split(","))
# Each line is converted to a tuple.
people = parts.map(lambda p: (p[0], p[1].strip()))

# The schema is encoded in a string.
schemaString = "name age"

fields = [StructField(field_name, StringType(), True) for field_name in schemaString.split()]
schema = StructType(fields)


# Apply the schema to the RDD.
schemaPeople = spark.createDataFrame(people, schema)

# Creates a temporary view using the DataFrame
schemaPeople.createOrReplaceTempView("people")

# SQL can be run over DataFrames that have been registered as a table.
results = spark.sql("SELECT name FROM people")

results.show()
# +-------+
# |   name|
# +-------+
# |Michael|
# |   Andy|
# | Justin|
# +-------+

+-------+
|   name|
+-------+
|Michael|
|   Andy|
| Justin|
+-------+